#index:
#    path: /
#    controller: App\Controller\DefaultController::index

hotel_stats:
  path: /hotel/{id}/reviews-stats
  # the controller value has the format 'controller_class::method_name'
  controller: App\Controller\HotelController::stats
  methods:    GET
